#!/usr/bin/env python3
"""Regenerate references/finding-codes.md from the source of truth.

The catalogue is extracted from the actual `report.add(...)` calls, so it cannot
drift from what the checks emit. Run after adding or changing any finding:

    python3 scripts/gen-finding-catalogue.py --write

Exits 1 when the checked-in catalogue is stale, which makes it usable as a CI gate:

    python3 scripts/gen-finding-catalogue.py --check
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "references" / "finding-codes.md"

PREFIX_GROUPS = [
    ("DSX-SPEC", "Contract structure", "Shape and vocabulary of ANALYSIS-SPEC itself."),
    ("DSX-EXP", "Experiment design", "Power, allocation, units, duration, multiplicity, peeking."),
    ("DSX-CAU", "Causal identification", "Whether the design licenses a causal reading."),
    ("DSX-STA", "Statistical validity", "Test selection, assumptions, and the reporting contract."),
    ("DSX-ML", "ML integrity", "Leakage, splits, metric choice, baselines, evaluation hygiene."),
    ("DSX-MET", "Metric semantics", "Definitions, reconciliation, drift, Simpson's paradox."),
    ("DSX-SQL", "SQL correctness", "Fan-out, NULL semantics, aggregation order."),
    ("DSX-CLM", "Claim discipline", "Causal language, evidence, generalisation, precision."),
    ("DSX-VIZ", "Visualization", "Encoding correctness, proportionality, uncertainty, access."),
    ("DSX-REP", "Reproducibility", "Seeds, environment, data identity, entrypoint."),
    ("DSX-DQ", "Data quality", "Hermetic assertions against DATA-PROFILE artifacts."),
    ("DSX-COH", "Coherence", "Question ↔ claim ↔ decision agreement."),
]


def _literal(node: ast.AST) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        parts = []
        for value in node.values:
            if isinstance(value, ast.Constant) and isinstance(value.value, str):
                parts.append(value.value)
            else:
                parts.append("<…>")
        return "".join(parts)
    return None


def extract(path: Path) -> list[tuple[str, str, str]]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    found: list[tuple[str, str, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if not (isinstance(func, ast.Attribute) and func.attr == "add"):
            continue
        if len(node.args) < 3:
            continue
        code = _literal(node.args[0])
        severity = _literal(node.args[1])
        title = _literal(node.args[2])
        if code and code.startswith("DSX-") and severity and title:
            found.append((code, severity, title.strip()))
    return found


def collect() -> list[tuple[str, str, str, str]]:
    rows: list[tuple[str, str, str, str]] = []
    sources = sorted((ROOT / "dsx").rglob("*.py"))
    for source in sources:
        module = source.stem if source.parent.name == "dsx" else f"checks/{source.stem}"
        for code, severity, title in extract(source):
            rows.append((code, severity, title, module))
    rows.sort(key=lambda r: r[0])
    seen: dict[str, tuple[str, str, str, str]] = {}
    for row in rows:
        if row[0] in seen and seen[row[0]][1:] != row[1:]:
            print(f"warning: {row[0]} declared twice with different text", file=sys.stderr)
        seen[row[0]] = row
    return list(seen.values())


def render(rows: list[tuple[str, str, str, str]]) -> str:
    lines = [
        "# Finding codes",
        "",
        "> Generated by `scripts/gen-finding-catalogue.py`. Do not edit by hand.",
        "",
        "Every check emits findings with a stable code. Codes are never renumbered, so",
        "a suppression or a reference in a review stays valid across versions.",
        "",
        "**Severity ladder.** `CRITICAL` — the result is invalid, not merely weak.",
        "`HIGH` — the conclusion is likely to be wrong or materially overstated.",
        "`MEDIUM` — a real defect that should be stated as a limitation if not fixed.",
        "`LOW` — presentation and hygiene.",
        "",
        "**Gate thresholds.** `plan` and `execute` block at CRITICAL; `verify` and",
        "`ship` block at HIGH.",
        "",
        f"**Total: {len(rows)} codes.**",
        "",
    ]
    for prefix, heading, blurb in PREFIX_GROUPS:
        group = [r for r in rows if r[0].startswith(prefix + "-")]
        if not group:
            continue
        lines += [f"## {heading} — `{prefix}-*`", "", blurb, "",
                  "| Code | Severity | Finding |", "|---|---|---|"]
        for code, severity, title, _module in group:
            safe_title = title.replace("|", "\\|")
            lines.append(f"| `{code}` | {severity} | {safe_title} |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    content = render(collect())
    if args.write:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(content, encoding="utf-8")
        print(f"wrote {TARGET.relative_to(ROOT)}")
        return 0
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != content:
            print("finding catalogue is stale — run with --write", file=sys.stderr)
            return 1
        print("finding catalogue is current")
        return 0
    print(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
